export const fastsAndFeasts = {
    year: "2025",
    amYear: "1741 – 1742",
    events: [
        {
            id: "0",
            eventTitle: "The Holy Nativity Feast",
            description: "",
            type: "feast",
            startDate: "January 7",
            endDate: "",
            noFish: false,
        },
        {
            id: "1",
            eventTitle: "The Circumcision Feast",
            description: "",
            type: "feast",
            startDate: "January 14",
            endDate: "",
            noFish: false,
        },
        {
            id: "2",
            eventTitle: "The Holy Epiphany",
            description: "",
            type: "fast",
            startDate: "January 19",
            endDate: "",
            noFish: false,
        },
        {
            id: "3",
            eventTitle: "Feast of the Wedding of Cana of Galilee",
            description: "",
            type: "feast",
            startDate: "January 21",
            endDate: "",
            noFish: false,
        },
        {
            id: "4",
            eventTitle: "Jonah's Fast",
            description: "(Nineveh)",
            type: "fast",
            startDate: "February 10",
            endDate: "February 12",
            noFish: true,
        },
        {
            id: "5",
            eventTitle: "Jonah's Feast",
            description: "(Nineveh)",
            type: "feast",
            startDate: "February 13",
            endDate: "",
            noFish: false,
        },
        {
            id: "6",
            eventTitle: "Presentation of the Lord into the Temple",
            description: "",
            type: "fast",
            startDate: "February 15",
            endDate: "",
            noFish: false,
        },
        {
            id: "7",
            eventTitle: "Holy Great Fast",
            description: "",
            type: "fast",
            startDate: "February 24",
            endDate: "April 19",
            noFish: true,
        },
        {
            id: "8",
            eventTitle: "The Feast of the Cross",
            description: "",
            type: "feast",
            startDate: "March 19",
            endDate: "",
            noFish: false,
        },
        {
            id: "9",
            eventTitle: "Annunciation Feast",
            description: "",
            type: "feast",
            startDate: "April 7",
            endDate: "",
            noFish: false,
        },
        {
            id: "10",
            eventTitle: "Lazarus Saturday",
            description: "",
            type: "fast",
            startDate: "April 12",
            endDate: "",
            noFish: false,
        },
        {
            id: "11",
            eventTitle: "Entry of our Lord into Jerusalem",
            description: "(Hosanna Sunday)",
            type: "fast",
            startDate: "April 13",
            endDate: "",
            noFish: false,
        },
        {
            id: "12",
            eventTitle: "Holy Pascha",
            description: "",
            type: "fast",
            startDate: "April 14",
            endDate: "April 18",
            noFish: false,
        },
        {
            id: "13",
            eventTitle: "Covenant Thursday",
            description: "",
            type: "fast",
            startDate: "April 17",
            endDate: "",
            noFish: false,
        },
        {
            id: "14",
            eventTitle: "Good Friday",
            description: "",
            type: "fast",
            startDate: "April 18",
            endDate: "",
            noFish: false,
        },
        {
            id: "15",
            eventTitle: "Glorious Feast of the Resurrection",
            description: "",
            type: "feast",
            startDate: "April 20",
            endDate: "",
            noFish: false,
        },
        {
            id: "16",
            eventTitle: "Thomas’ Sunday",
            description: "",
            type: "fast",
            startDate: "April 27",
            endDate: "",
            noFish: false,
        },
        {
            id: "17",
            eventTitle: "Martyrdom of St. Mark the Evangelist",
            description: "",
            type: "fast",
            startDate: "May 8",
            endDate: "",
            noFish: false,
        },
        {
            id: "18",
            eventTitle: "The Holy Feast of Ascension",
            description: "",
            type: "feast",
            startDate: "May 29",
            endDate: "",
            noFish: false,
        },
        {
            id: "19",
            eventTitle: "Entry of the Lord into Egypt",
            description: "",
            type: "fast",
            startDate: "June 1",
            endDate: "",
            noFish: false,
        },
        {
            id: "20",
            eventTitle: "The Holy Pentecost Feast",
            description: "",
            type: "feast",
            startDate: "June 8",
            endDate: "",
            noFish: false,
        },
        {
            id: "21",
            eventTitle: "The Apostles' Fast",
            description: "",
            type: "fast",
            startDate: "June 9",
            endDate: "July 11",
            noFish: false,
        },
        {
            id: "22",
            eventTitle: "The Apostles' Feast",
            description: "(Martyrdom of St. Peter & St. Paul)",
            type: "feast",
            startDate: "July 12",
            endDate: "",
            noFish: false,
        },
        {
            id: "23",
            eventTitle: "St. Mary's Fast",
            description: "",
            type: "fast",
            startDate: "August 7",
            endDate: "August 21",
            noFish: false,
        },
        {
            id: "24",
            eventTitle: "Transfiguration Feast",
            description: "",
            type: "feast",
            startDate: "August 19",
            endDate: "",
            noFish: false,
        },
        {
            id: "25",
            eventTitle: "Assumption of St. Mary's Body",
            description: "",
            type: "fast",
            startDate: "August 22",
            endDate: "",
            noFish: false,
        },
        {
            id: "26",
            eventTitle: "The Nayrouz Feast",
            description: "(Coptic New Year)",
            type: "feast",
            startDate: "September 11",
            endDate: "",
            noFish: false,
        },
        {
            id: "27",
            eventTitle: "The Feast of the Cross",
            description: "(Three days)",
            type: "feast",
            startDate: "September 27",
            endDate: "September 29",
            noFish: false,
        },
        {
            id: "28",
            eventTitle: "The Holy Nativity Fast",
            description: "",
            type: "fast",
            startDate: "November 25",
            endDate: "January 6",
            noFish: false,
        },
    ],
};
